export { MatchesModule } from './matches.module.js';
export { MatchEntity } from './entities/match.entity.js';
export { MatchPlayerEntity } from './entities/match-player.entity.js';
export { MatchConfirmationEntity } from './entities/match-confirmation.entity.js';
export { AuditLogEntity } from './entities/audit-log.entity.js';
export { MatchService } from './services/match.service.js';
export { ConfirmationService } from './services/confirmation.service.js';
export { AdminOverrideService } from './services/admin-override.service.js';
export { MatchRepository } from './repositories/match.repository.js';
export type { ConfirmationStatusResult } from './services/confirmation.service.js';
export type { AdminOverrideResult } from './services/admin-override.service.js';
export { CreateMatchDto } from './dto/create-match.dto.js';
export { UpdateMatchDto } from './dto/update-match.dto.js';
export { AddPlayersDto } from './dto/add-players.dto.js';
export { SubmitResultDto } from './dto/submit-result.dto.js';
export { ListMatchesDto } from './dto/list-matches.dto.js';
export { AdminOverrideResultDto } from './dto/admin-override.dto.js';
export type { MatchType, MatchStatus } from './entities/match.entity.js';
export type { Team } from './entities/match-player.entity.js';
