services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    working_dir: /workspaces/foosball
    volumes:
      - ..:/workspaces/foosball:cached
    depends_on:
      - redis
      - mysql
    ports:
      - 3000:3000
      - 8000:8000

  redis:
    image: redis:7.0
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foosball
      MYSQL_USER: foosball
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  redis-data:
  mysql-data:

networks:
  default:
    driver: bridge